name = "smail-app"
compatibility_date = "2025-01-15"
compatibility_flags = ["no_handle_cross_request_promise_resolution"]
main = "./workers/app.ts"

[observability]
enabled = true

[[send_email]]
name = "EMAIL"

[[kv_namespaces]]
binding = "KV"
id = "YOUR_KV_NAMESPACE_ID_HERE"

[[d1_databases]]
binding = "DB"
database_name = "smail-database"
database_id = "YOUR_D1_DATABASE_ID_HERE"
preview_database_id = "YOUR_D1_DATABASE_ID_HERE"
migrations_dir = "./app/db/migrations"

[[r2_buckets]]
binding = "ATTACHMENTS"
bucket_name = "smail-attachments"
preview_bucket_name = "smail-attachments-preview"

[assets]
directory = "./build/client"